on:
  workflow_dispatch:
name: Create Release

jobs:
  create-release:
    if: ${{ github.event.pusher.name != 'github action' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main
          dry_run: false
