name: Build and Upload Release

on: push

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for uploading to releases
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git tags
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: make test